# Generated by Django 4.1.6 on 2023-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Roll", models.CharField(max_length=2)),
                ("Address", models.TextField(max_length=200)),
                ("Email", models.EmailField(max_length=100)),
                ("Phone", models.CharField(max_length=10)),
            ],
        ),
    ]
